language: node_js
node_js:
  - 12
cache: npm

script:
  - npm run build

after_success:
  - npm run lint
  - bash <(curl -s https://codecov.io/bash)
  - ./scripts/post-build.sh

deploy:
  provider: npm
  edge: true
  api_token: $NPM_API_TOKEN
  on:
    branch: master
