language: node_js
node_js:
  - 12
cache: npm

notifications:
  slack:
    secure: "vuXGp1K6hF/jKkrmC+higEVhPpm587SBeQay9GqHkiO3hAl2663BosLUYRiCQx37K8ord+cZwksRtuCTcTsq9eYC53PVWq5mxhbQm8xQQfI55oHKA8FmN75HzXNqMiUFIexRCDxXNb5RxkIsi7FUS/mv2t/GsBj44oB6AKWehJOfhgjROyObqf2PwD0/TS+yVAWnGKvBmUuNoh7bIPae53H9lqU4xWGpouK5b+ZQqrUJcN0/MleX/LtXdfk3rur1+6fLorVELVPwI8XASIxOG6XBQaoX4LSgfDhUZCbhG4fS43IxfO+JPrnYXu1TchwFjfxykLiPcqjb8nGN6R8eIf7yzZJ6NMfruXmKCh0pFISUbpe51MsyDW7ZjsYfMdvlCak9YeHY3jlY06Ko1zosccAr8Arku1hKwA1zyXUFsa4oiVN3EI2MGGZ4eLF3lQF/3E3ZPbGOXktcvTuwYEnYqu1XEq65H/Pe+uGwCeduHAubYBtBEy4t0xGPtol5r6pvnI/0bdJmIiAZgqebAp1h6+VX8yIuldLlREBN3tVtPhNCs6OYyNn8u4dPTJVCSEk2rW/lDyKGDsRDJaad/UbH9Vn9SCfezCMqbFM9wPH9Tv6p8fh58cWd+HG2Zw7rFXP3cbb4iJlODA+JliIhStA5rLMBdZ9T4LlbmViHtgbH/bM="

script:
  - npm run test
  - npm run build

after_success:
  - npm run lint
  - bash <(curl -s https://codecov.io/bash)
  - ./scripts/post-build.sh

deploy:
  provider: npm
  edge: true
  api_token: $NPM_API_TOKEN
  on:
    branch: master
