language: node_js
node_js:
  - 12
cache: npm

notifications:
  slack:
    secure: "e3sJmY+eJoeBWuOf/y2aVh5eqhHqZm0/ZP60HYFGEhGbRdiuEFZSBhPm5tiN4JRnqUUa1nyVDXvPC9GH01Y+xZZIJKvBG3fU8QGGwtNt5hPSRRyV+giA+HanNJqmsr4HLbz10bedB+t1RxbxJWLXl7vIp5LQCdGQmE4dz5YElBoMylA02kVvf7P23J+bViVCa/jR1Fq0KbS2L+GUPucH8zQvZ71/lxeisBORuwWYoseSQZVWOTA8Q9WHD0CbqTj3ZyhYpclX0WgTqH8QxmIn64Jz63BuqH6y8EjA355JvKqnA/Tq9Q+5OM8A64JvLHGVt7qf3Tz9kM/jeqm5CcXjAhF2eg3gSbIoO4vaDIx0vyQAaf837MQJ+aIrWlCS/SnqjnG085Tz8nwU2VpA43ynS+Y7+STcyMAgnysEyODhScCjOhdVQz1C6ZMa2HLRb8UVlTiF3BbghfzjbKQ1d4QZ4Ye7soRMc8RaIl1DwdYL1ei/LrXWTLgDKFhzfxLomuCUqe2hvu+t4vnEYsmptKET8ruoKS+LOlOfUqLJX0c7GsAnj5H4V5bTBsO16327OvunY1Nb9NsU2UaGFdQ88t26+9fyzaE5wJlEZEMjrpKRqqHCfXlwaeK3+Ma973bsxlS7RqMgJ9hgNzDnBrf/sRzGop08BklyOW3wdXmEcJvxa/o="

script:
  - npm run test
  - npm run build

after_success:
  - npm run lint
  - bash <(curl -s https://codecov.io/bash)
  - ./scripts/post-build.sh

deploy:
  provider: npm
  edge: true
  api_token: $NPM_API_TOKEN
  on:
    branch: master
