language: node_js
node_js:
  - 12
cache: npm

notifications:
  slack:
    secure: "czIhoxlf/e6IsWEoUGbSMKLO4VanPCPbaJIW+eoAC8DStmIGNHIZmOO1H6UH0XEkJG1XhQ5BaY4pyGxzc+i1qttEarx257kqgB2phuTBbZrtEbl9qsIThzRrfP2iEQqwLo27gVA2yXjPnVXyA893w5oRALf/C0FUGUMqAOxtb1evFOVyAxzj2ZoQVnzNEaLmMJa8uoUgdKsyAxr4iRrgHvqydUAIDR4IT78ada/XhkZ9aCt3a4+YHKidk4YDxPUZiLAMyP1ccMioOppFXVyTFDyYxjBqV1Ktlsamknj0nr9P4CTq3MJYHT8XBs6+quYYBFfhwCEZzfjh04AoTrnk2dRW2YdhUs0U6fBVACLXAm7Qh6bmI+NMT5AoLswH7zsEDSmp11qBjHn7niQRJCFZ2rxW5yKh5MIsFq7n6UVvJs5++pOn9Ho4pP/GNHThDovc4P9AkHXuYykSQ2upp27s3WthFE+rpCQJzXyAu8X/350baJdWEohwEU5QuhtjrJtHBW9AxSO+UpvyxG9p+C2JFC9xmC5tMa1UgGBKWGzaUWTjQ9KszSP4RKoaNXTPTMfZYHd3MSVEFVINl9bV6B/LZRGoBkGTaNyDJIP7t7STGRiFPrkh8EwCA10J/TKP4qogNmLA/Gjho+nei/jNIMxo13DI9CgBLz8mZDbKO/scaGk="

script:
  - npm run test
  - npm run build

after_success:
  - npm run lint
  - bash <(curl -s https://codecov.io/bash)
  - ./scripts/post-build.sh

deploy:
  provider: npm
  edge: true
  api_token: $NPM_API_TOKEN
  on:
    branch: master
