language: node_js
node_js:
  - 12
cache: npm

notifications:
  slack:
    secure: fwMU/Gdhh7LPIkx9VnmwITXQE0SSTg2xMrJE6pg4XB1PtIPENcQWpkQbcvHtHE84u61PJyjw0U4THha9bzimZkgfLzk8EuH9kVNPq9hcYbep9IlDz/ZleCExVKCx0PnhNoqb1YETgbhuzM8pg88BsSo0u+U5Qqfi+wUkIehbvztu9OjpUsrQrnO4+oeLOVqXVrRE+s/iE20mE7/YECZl6ZNdIeCjX7Bt6k90ozr0unfZVa+p+7rY29gu0Vg12bEXckyZVjUnaEwWRu7ZWr/VCF+qyg3MBT6/npBMf+4tXQkRcY7031ieWveiHl0XLec0rJx6JCy0YnAcKG4WzpUNEf6U0sItueoUHgz6mMUnNLB4ptGQsMgYEmcV0/dbCAlHKZqpF6Ymi5u+7xIWWVK8BZe4l4BBlIRLtlRp2mcEfU6rcBCneD32fgmN9Hu2s3oKp5RwwSnUcpOG6j2JXZEX5Z0fYHsFJy5hGIE0/3/XblGvvQU6fUr/ECdev7HSfvdP7XEcvqfjxOK4QTm5Ub6D2GTNhoA7d1LaUCK37PBFJwNTJ8UgQKfiHCKi0ZyTiM26dgEPcZxSIXgiNA4AuoZB3cy27cntUZVRi5w4MMezWE0Z/QBcoI+FgHu/PNFpKups1MPYWMoG978mH4+QwqkP8HGshLob5Kq5Vt5gu4IXbkI=

script:
  - npm run build
  - npm run test

after_success:
  - npm run lint
  - bash <(curl -s https://codecov.io/bash)
  - ./scripts/post-build.sh

deploy:
  provider: npm
  edge: true
  api_token: $NPM_API_TOKEN
  on:
    branch: master
