language: node_js
node_js:
  - 12
cache: npm

notifications:
  slack:
    secure: fpWMerGMC98evwrVr4mkWd9UAvOHzqh9ODBNPATi35kAYtJC28w+YmEqclvJM7gIyDEjI5T8BAPIE/izv9y2aF928TlG9kgWxiCDcKuvnWGK/px1VazXQ56pQzlAdohWufgnRFvK2MVKIQlmc3wbFKM3MQ5qzHREuJ8heWO1v3GsBGceLM+UeskOE4GFstkkHCv36aqH0TV5PbzxbtzsJxRRd8giH8yU9ehxXFY007r942AUDPb7BNtOL0iFlgAh7FPpmGD3wtMBlctEoXMxJhDEBpjHAKp4OJITbwCblI1RqY4+d6uK8+nnqBThL17VxpovlW7JfkImjsSC+YFtYwmC4rY+oA90zAceC4ppJEhyEBy+IYM9ivGfeDyBceO0kOvEHVi6kr5dV081JbL2LoRvSgtMIfy8x2w2e7OayLAU3zZrq6oM0dEo9VIPf75a/gNMkc3CSLiBgWdaq8sCHxx0G4bXSQsCkN+CkMvj+AwKTAdvdku/+zU8erul8yk/D868308ZOE5Lms0QT1vn8ARksGBJQgMGLQ4fElDNcTz87aoseksnfTwyiIMPbcC8VbxrtigAODm9Ys+BgqI3kx6ikK42CNUcZmpeguoOxMigFSNE4nsP+kc7Yc96kAyu72eANkwr4wLXAObhrleyXnN28psq9hN/L1crTzLoT88=

script:
  - npm run test
  - npm run build

after_success:
  - npm run lint
  - bash <(curl -s https://codecov.io/bash)
  - ./scripts/post-build.sh

deploy:
  provider: npm
  edge: true
  api_token: $NPM_API_TOKEN
  on:
    branch: master
