language: node_js
node_js:
  - 12
cache: npm

notifications:
  slack:
    secure: Us6cAWLaFucYFbXkidkBc3Ctwcbo+40xR4+sKwrjWlNoW5tKlmyp//Tz5+YkeojBOA84t/z3VBvjDsmw4sO9xf99M2JvSbo2PZH3lVtILtcjX8YnRwCNTdkjZaFZ6p3IJPw9sGCrbtQfmoWftZ1BG1NkrwRiqkQPVlrzVUkMrXxlqsgepM41ibZT1Wp2akVVjDtAgNhLoTa3QANc+TTYxJ/PMLXfcfAT9RZz2clDP6r6bCpG/mjU9ZStBFGkyDRQAgfOH6rvEkhe1ji8gSTjPKp/2nT+Ug9yOio4WVvilsF+IMZdNWgpkkm4gNFnoTeD3q4r7rpUqigLp7nV+pI/5Brc0dBlDXX1H5wvDUG2/Cu+xBswb012QNEjC7t2iBnOvK5FpBJa1U5tnkKWQdMZ26lhfiZqgOSKFND5bhZs9o/5PFlmxvEw+lHg13JC69vvchwRL1I8sCeLuFFy3L8y5kAdxDC1SwxV9s5KTroLz+PNc7NUgW4duhQvtMT/ToyBYvSFrGUeztxO8T1OVaRvQ3ggK0r1YJHk4tPJnVx1ggPcUg5P+JDAGbYSAm/zLaOh8FhAzzktGgQs2l90kol5lu79XSeLkpexu8ju8xkissNLX+VLln9v4j3rKwj+mTTW10Ic19Oq89hhRLrRkJTKs9n7xkl9avUmBiWXDV79fF8=

script:
  - npm run test
  - npm run build

after_success:
  - npm run lint
  - bash <(curl -s https://codecov.io/bash)
  - ./scripts/post-build.sh

deploy:
  provider: npm
  edge: true
  api_token: $NPM_API_TOKEN
  on:
    branch: master
